apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-rating-app
  labels:
    app: book-rating-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-rating-app
  template:
    metadata:
      labels:
        app: book-rating-app
    spec:
      containers:
        - name: book-rating-app
          ports:
            - containerPort: 3000
