name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request: 
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }} # fdimatteo/book-rating-app
  IMAGE_NAME: ${{ github.event.repository.name }} # book-rating-app
  CONTAINER_NAME: ${{ github.event.repository.name }} # book-rating-app
  IMAGE_TAG_SHA: ghcr.io/${{ github.repository }}:${{ github.sha }}
  COMMIT_SHA: ${{ github.sha }}
  GIT_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'n/a' }}
  AZURE_CLUSTER_NAME: myAKSCluster
  AZURE_RESOURCE_GROUP: bookRatingAppGroup

jobs:
  
  lint:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
 
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.IMAGE_TAG_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            GIT_TAG=${{ env.GIT_TAG }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar

    outputs:
      tags: ${{ steps.meta.outputs.tags }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: development

    permissions:
      packages: write
      id-token: write
      attestations: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Retrieve build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ runner.temp }}

      - name: Load Docker image
        run: |
          docker load -i ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar
          docker image ls -a

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          if [ github.ref_type == 'tag' ]; then
            docker tag ${{ env.IMAGE_TAG_SHA }} ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.GIT_TAG }}
            docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.GIT_TAG }}
          fi
          docker push ${{ env.IMAGE_TAG_SHA }}
          docker tag ${{ env.IMAGE_TAG_SHA }} ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest

    outputs:
      tags: ${{ needs.build.outputs.tags }}

  deploy-dev-local:
    needs: publish
    runs-on: self-hosted
    environment: development
    
    steps:
      - name: Deploy
        id: action-ssh
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            podman login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            podman pull ${{ env.IMAGE_TAG_SHA }}
            podman stop ${{ env.CONTAINER_NAME }} || true
            podman rm ${{ env.CONTAINER_NAME }} || true
            podman run -d --name ${{ env.CONTAINER_NAME }} -p 3000:3000 ${{ env.IMAGE_TAG_SHA }}

  deploy-dev-az:
    needs: publish
    runs-on: ubuntu-latest
    environment: development

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/setup-kubectl@v4

    - uses: Azure/aks-set-context@v4
      with:
          cluster-name: ${{ env.AZURE_CLUSTER_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}

    - uses: Azure/k8s-deploy@v5
      with:
          action: deploy
          images: |
            ${{ env.IMAGE_TAG_SHA }}
