name: Deploy to Local Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/gh-actions


jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        id: action-ssh
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ~/book-rating-app
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            podman-compose down
            podman-compose up -d
