name: Deploy to Local Server

on:
  workflow_dispatch: # Manual trigger
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - feature/gh-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/book-rating-app
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            podman-compose down
            podman-compose up -d
